package ex2;

import java.io.FileNotFoundException;

public class Presenter {

	public static void main(String[] args) {
		Logic l = new Logic();

		//compiler knows calling the "openFile" method can cause errors, so it knows the method must be called inside a try-catch block 
		try{
			l.openFile("hello.txt");
		}catch(FileNotFoundException e){
			System.out.println(e);
		}

	}

}
